version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      # Logging in to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s5o7d0z2
      #- docker login --username AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws/s5o7d0z2
      - REPOSITORY_URI=public.ecr.aws/s5o7d0z2/vishal-demo-repo
      # Storing the commit hash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      # Building using Maven
      - echo "Running Mvn"
      - mvn clean package
      # Building the Docker image
      - echo "Building the Docker image"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      # Check if the build stage is successful
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"1/" ]; then exit 1; fi"
      - echo Build completed on `date`
      # Pushing the image to ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
